version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      actions-deps:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      npm-sdk-deps:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directories:
      - "/demos/next"
      - "/demos/next-oidc"
      - "/demos/next-sdjwt-workshop"
      - "/demos/node"
    schedule:
      interval: "monthly"
      day: "monday"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      npm-demo-deps:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directories:
      - "/integration-tests/e2e-tests"
      - "/integration-tests/node/cjs"
      - "/integration-tests/node/esm"
      - "/integration-tests/node/ts-cjs"
      - "/integration-tests/node/ts-esm"
    schedule:
      interval: "monthly"
      day: "monday"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      npm-test-deps:
        patterns:
          - "*"
