branches:
  - 'master'

plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - [ '@semantic-release/changelog',
    {
      changelogFile: 'CHANGELOG.md'
    }
  ]
  - [ '@semantic-release/exec',
    {
      prepareCmd: 'npm version ${nextRelease.version} --git-tag-version false'
    }
  ]
  - [ '@semantic-release/exec',
    {
      prepareCmd: 'npm publish'
    }
  ]
  - [ '@semantic-release/exec',
    {
      prepareCmd: 'yarn --cwd integration-tests/e2e-tests add @input-output-hk/atala-prism-wallet-sdk@^${nextRelease.version}'
    }
  ]
  - [ '@semantic-release/git',
    {
      assets: [
        'package.json',
        'package-lock.json',
        'CHANGELOG.md',
        'integration-tests/e2e-tests/**/*'
      ],
      message: 'chore(release): release ${nextRelease.version}\n\n${nextRelease.notes}'
    }
  ]
  - [ "semantic-release-slack-bot",
    {
      notifyOnSuccess: true,
      notifyOnFail: true,
      markdownReleaseNotes: true,
      onSuccessTemplate: {
        text: "A new version of `$package_name` successfully released!\n
        Version: `$npm_package_version`\n
        Tag: $repo_url/releases/tag/v$npm_package_version\n
        \n
        Release notes:\n
        $release_notes"
      }
    }
  ]
