branches:
  - 'master'
  - 'ci/pipelines'

plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - [ '@semantic-release/changelog', { changelogFile: 'CHANGELOG.md' } ]
  - [ '@semantic-release/exec', {
    prepareCmd: 'yarn publish --no-git-tag-version --access restricted --new-version ${nextRelease.version}' } ]
  - [ '@semantic-release/git', {
    assets: [ 'package.json' , 'yarn.lock' , 'CHANGELOG.md' ],
    message: 'chore(release): release ${nextRelease.version}

    ${nextRelease.notes}' } ]
  - [ "semantic-release-slack-bot", {
    notifyOnSuccess: true,
    notifyOnFail: true,
    markdownReleaseNotes: true,
    onSuccessTemplate: {
      text: "A new version of `$package_name` successfully released!\n
        Version: `$npm_package_version`\n
        Tag: $repo_url/releases/tag/$npm_package_version\n
        \n
        Release notes:\n
        $release_notes" } } ]
