name: Continuous integration

concurrency:
  group: ${{ github.head_ref }}${{ github.ref }}-wallet-sdk
  cancel-in-progress: true
on:
  pull_request:
    branches:
      - "master"

defaults:
  run:
    shell: bash

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.ATALA_GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          scope: "@input-output-hk"
          registry-url: "https://npm.pkg.github.com"

      - name: Install
        run: npm install

      - name: Eslint
        run: npx eslint .

      - name: Build
        run: npm run build

      - name: Run coverage test
        run: npm run coverage

      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@v1.0.23
        with:
          coverage-summary-path: coverage/coverage-summary.json
          junitxml-path: coverage/junit.xml
          junitxml-title: JUnit

      - name: Publish lcov report
        uses: actions/upload-artifact@v3
        with:
          name: lcov-report.zip
          path: coverage/lcov-report
          if-no-files-found: error
