name: Continuous integration

concurrency:
  group: ${{ github.head_ref }}${{ github.ref }}-wallet-sdk
  cancel-in-progress: true
on:
  pull_request:
  push:
    branches:
      - "master"

defaults:
  run:
    shell: bash

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.ATALA_GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          scope: "@input-output-hk"
          registry-url: "https://npm.pkg.github.com"

      - name: Install
        run: npm install

      - name: Eslint
        run: npx eslint .

      - name: Build
        run: npm run build

      - name: Build tests
        run: npm run build:test

      - name: Test node
        run: npm run test:node

      - name: Test browser
        run: npm run test:browser

      - name: Check coverage
        run: yarn coverage:check
