name: End-to-end tests

concurrency:
  group: ${{ github.head_ref }}${{ github.ref }}-e2e
  cancel-in-progress: true

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:
    inputs:
      mediatorOobUrl:
        required: true
        description: Mediator out-of-band url
        default: https://sit-prism-mediator.atalaprism.io/invitationOOB
      prismAgentUrl:
        required: true
        description: Prism-agent server url
        default: https://sit-prism-agent-issuer.atalaprism.io/prism-agent
      publishedDid:
        required: false
        description: Published DID
      jwtSchemaGuid:
        required: false
        description: JWT schema GUID
        default: 
      anoncredDefinitionGuid:
        required: false
        description: Anoncred definition GUID
      apiKey:
        required: false
        description: Authorization key
  # pull_request:
  #   branches:
  #     - master
  push:
    branches:
      - master

jobs:
  run-e2e-tests:
    name: "Run"
    runs-on: ubuntu-latest

    steps:
      - name: Mask apikey
        env:
          APIKEY: ${{ inputs.apiKey || secrets.APIKEY }}
        run: echo "::add-mask::${{env.APIKEY}}"

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
          submodules: 'true' 

      - name: Setup Node.js for @input-output-hk
        uses: actions/setup-node@v3
        env:
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          node-version: "lts/*"
          registry-url: https://npm.pkg.github.com/
          scope: "@input-output-hk"

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install wasm-pack
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Setup Node.js for @hyperledger-labs
        uses: actions/setup-node@v3
        env:
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          node-version: "lts/*"
          registry-url: https://npm.pkg.github.com/
          scope: "@hyperledger-labs"

      - name: Pack atala-prism-wallet-sdk
        if: github.event_name == 'pull_request'
        run: |
          npm install
          npm run build
          npm pack
          echo "PACKAGE_NAME=$(find . -maxdepth 1 -name atala-prism-wallet-sdk-* | tr -d '\n')" >> "$GITHUB_ENV"
  
      - name: Install local dependency
        if: github.event_name == 'pull_request'
        working-directory: integration-tests/e2e-tests
        run: |
          yarn
          yarn add "../../${{ env.PACKAGE_NAME }}"

      - name: Install dependencies
        working-directory: integration-tests/e2e-tests
        run: yarn

      - name: Run tests
        env:
          MEDIATOR_OOB_URL: ${{ inputs.mediatorOobUrl || vars.MEDIATOR_OOB_URL }}
          PRISM_AGENT_URL: ${{ inputs.prismAgentUrl || vars.PRISM_AGENT_URL }}
          PUBLISHED_DID: ${{ inputs.publishedDid || vars.PUBLISHED_DID }}
          JWT_SCHEMA_GUID: ${{ inputs.jwtSchemaGuid || vars.JWT_SCHEMA_GUID }}
          ANONCRED_DEFINITION_GUID: ${{ inputs.anoncredDefinitionGuid || vars.ANONCRED_DEFINITION_GUID }}
          APIKEY: ${{ inputs.apiKey || secrets.APIKEY }}
        working-directory: integration-tests/e2e-tests
        run: yarn test:sdk

      - name: Generate end-to-end report
        working-directory: integration-tests/e2e-tests
        run: yarn test:sdk:report

      - name: Add notes to summary
        working-directory: integration-tests/e2e-tests
        run: cat notes >> $GITHUB_STEP_SUMMARY

      - name: Publish Serenity report
        uses: actions/upload-artifact@v3
        with:
          name: atala-prism-sdk-ts
          path: integration-tests/e2e-tests/target/site/wallet-sdk-ts
          if-no-files-found: error
